---

- name: Copy binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/baccli
    mode: 0755
  notify: restart baccli

- name: Copy service
  template:
    src: baccli.service.j2
    dest: /etc/systemd/system/baccli.service
  notify: systemctl

