---

- name: Fetch genesis.json
  fetch: "src=/home/bacd/.bacd/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bacd

- name: Fetch config.toml
  fetch: "src=/home/bacd/.bacd/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bacd

