# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# The minimum gas prices a validator is willing to accept for processing a
# transaction. A transaction's fees must meet the minimum of any denomination,
# and it must be positive integer,
# specified in this config (e.g. 1 token;not less than 1 token, and now the token1 must be ubac).
minimum-gas-prices = "1nbac"
